version: "3.4"

services:
  app:
    build: ./app
    container_name: python-flask-app-container
    links:
    - db
    ports:
      - "8085:5000"
    volumes:
      - ./app:/app/
    networks:
      - mysql-python-app-network
  
  db:
    image: mysql:8.0
    container_name: mysql-flask-app-container
    ports:
      - "32000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - mysql-python-app-network

networks:
  mysql-python-app-network:
    name: mysql-python-app-network
volumes:
  mysql-python-app-volume:
  mysql-python-app-volume-config:
